# Generated by Django 2.1 on 2018-09-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('sgender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
        ),
    ]
